# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-13 19:05
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two_factor', '0005_auto_20160224_0450'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonedevice',
            name='extension',
            field=models.CharField(blank=True, max_length=4, validators=[django.core.validators.RegexValidator('^[0-9]{0,4}$', 'Extension must be blank or up to 4 numeric values')], verbose_name='extension'),
        ),
    ]
